CREATE USER 'prox_user'@'localhost' IDENTIFIED BY 'prox_pass';
GRANT CREATE, ALSTER, DROP, INSERT, UPDATE, DELETE, SELECT, REFERENCES, RELOAD
on *.* TO 'prox_user'@'localhost' WITH GRANT OPTION;

FLUSH PRIVILEGES;

CREATE DATABASE IF NOT EXISTS prox_db_system;